# Working directory
root = "."
tmp_dir = "_tmp"

[build]
cmd = "GOCACHE=/src/_tmp/.cache go build -buildvcs=false -o ./_tmp/dianomi-server ./main.go"
bin = "_tmp/dianomi-server"
full_bin = "APP_ENV=dev APP_USER=air ./_tmp/dianomi-server"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["assets", "_tmp", "vendor", "website"]
exclude_unchanged = true
follow_symlink = true
delay = 150 # ms
stop_on_error = true

[log]
time = true
main_only = false

[misc]
clean_on_exit = true